FILE2MOD = file2mod.py 
MOD2SEC = mod2sec.py 
OCUPDATE = oc-update.sh

DESTDIR ?= /usr/local/bin/

all:
	

install:
	install -m 755 $(FILE2MOD) $(DESTDIR) 
	install -m 755 $(MOD2SEC) $(DESTDIR) 
	install -m 755 $(OCUPDATE) $(DESTDIR) 

